// This file was autogenerated by calcdeps.py
goog.addDependency('../../../alltests.js', [], []);
goog.addDependency('../../../collection.js', ['mvc.Collection'], ['mvc.Model', 'goog.events.EventTarget']);
goog.addDependency('../../../collection_test.js', [], ['mvc.Collection', 'mvc.Model', 'goog.testing.PropertyReplacer', 'goog.testing.jsunit']);
goog.addDependency('../../../control.js', ['mvc.Control'], ['goog.dom', 'goog.object', 'goog.ui.Component']);
goog.addDependency('../../../control_test.js', [], ['mvc.Control', 'goog.dom', 'goog.testing.jsunit']);
goog.addDependency('../../../model.js', ['mvc.Model', 'mvc.model.Schema'], ['goog.array', 'goog.dom', 'goog.events', 'goog.events.EventTarget', 'goog.object']);
goog.addDependency('../../../model_test.js', [], ['mvc.Model', 'goog.testing.jsunit']);
goog.addDependency('../../../router.js', ['mvc.Router'], ['goog.events', 'goog.History']);
goog.addDependency('../../../router_test.js', [], ['mvc.Router', 'goog.testing.ContinuationTestCase', 'goog.testing.jsunit']);
goog.addDependency('../../../test_deps.js', [], []);
goog.addDependency('../../../sync/ajax.js', ['mvc.AjaxSync'], ['mvc.sync', 'goog.net.XhrManager']);
goog.addDependency('../../../sync/local.js', ['mvc.AjaxSync'], ['goog.storage.Storage', 'goog.storage.mechanism.HTML5LocalStorage']);
goog.addDependency('../../../sync/sync.js', ['mvc.ync'], []);
goog.addDependency('../../../testApp/testApp.js', [], []);
